# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba8519cb5a196ccb5c48f3228c150253ec5ba55406abefa6dd44c341dd94eee2f6ab2aa484ffda5687e054782b27641083df4e219484b16863dde14bd5dbb4fe

test:
  secret_key_base: 16a85ae14ca8aecbaab5c1b7aa633aca3272f62c67025490dbdcd8a57c5b9f353b0248c1f61b12d3a193b7fba670ee5a5d075a90acbf5235ca58f3ebaf521782

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
